# Dual-language ~ Perl & Node.JS.
# E-Access Bulletin.

language: perl

perl: "5.24"

git:
  depth: 8

# http://stackoverflow.com/questions/35367357/error-object-has-no-method-endswith-on-custom-grunt-task
before_install: nvm install v8.1

install:
  - npm install
  - npm run install-cpan

script: npm test

after_script:
  - npm run count
  #- npm run cat-log
  - npm run pa11y-ci

# End.
